### PR TITLE
Add old blog posts

### PR DESCRIPTION
**Pull request by scottnuma**

### CODE REVIEW

**Comment by scottnuma** [comment]
darn - just realized i should've generated using categories instead of tags

**Comment by jiangdaniel** [comment]
This PR might be better to merge after #239 is settled

**Comment by dwai213** [comment]
Hmm, is this PR intended to allow a general person to use fill out a csv to add a blog entry to the site (by regenerating all of the posts + new post)?

**Comment by jiangdaniel** [comment]
I think Scott is pushing the python file just in case we ever need it in the future.  I'm guessing that new blog posts are still supposed to be written following the instructions on https://github.com/pioneers/website/wiki/Creating-Blog-Posts.

**Comment by scottnuma** [comment]
Yeah the wiki still has the recommended instructions for creating blog posts. I added the python file just in case we ever need to pull posts from a .csv again.

**Comment by dwai213** [comment]
Oh gotcha, this is for archival purposes!
Thanks for the clarification

**Pull request merged**
