### PR TITLE
[WIP] Deployment update

### PR DESCRIPTION
**Pull request by scottnuma**
This PR seeks to update how the website runs on the server and bring it to better match how we develop.

- also seeks to bring us the benefits of the latest version of Jekyll: live reloading and no more F5!
- when these commits are deployed, we will need to monitor the server for success

This PR should be reviewed and merged after #485 for best comparison

### CODE REVIEW

**Comment by scottnuma** [comment]
Updating the [Web Dev Setup](https://docs.google.com/document/d/14hePb_iyx7f3JbPkDooNjDOiIoC6gGtd7n-FRceF1GE/edit#heading=h.jpthleuezp3k)

**Comment by scottnuma** [comment]
Hmm, probably around 2 am in CA is good. so likely 5 pm your time? During the summer at that time I doubt many people would notice any interruption.

**Comment by kev-chien** [comment]
I tried to deploy but this happened:

Step 7/7 : CMD serve
 ---> Running in 675eec10102d
 ---> 90a0fb1dba91
Removing intermediate container 675eec10102d
Successfully built 90a0fb1dba91
Successfully tagged dokku/website:latest
-----> Releasing website (dokku/website:latest)...
-----> Deploying website (dokku/website:latest)...
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
-----> No Procfile found in app image
-----> DOKKU_SCALE file found (/home/dokku/website/DOKKU_SCALE)
=====> web=1
remote: Error: No public port '4000/tcp' published for 8960ea30e6f314371ce4e80a61b10f14306a050d1372592a854f69b86944eb57
-----> Attempting pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
8960ea30e6f314371ce4e80a61b10f14306a050d1372592a854f69b86944eb57
remote: App container failed to start!!
=====> website web container output:
       /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in 'block in materialize': Could not find concurrent-ruby-1.0.5 in any of the sources (Bundler::GemNotFound)
        from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in 'map!'
        from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in 'materialize'
        from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in 'specs'
        from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in 'specs_for'
        from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in 'requested_specs'
        from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in 'requested_specs'
        from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in 'setup'
        from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:92:in 'setup'
        from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.2/lib/jekyll/plugin_manager.rb:38:in 'require_from_bundler'
        from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.2/bin/jekyll:13:in '<top (required)>'
        from /usr/bin/jekyll:22:in 'load'
        from /usr/bin/jekyll:22:in '<main>'

The last error message "Could not find concurrent-ruby-1.0.5" was repeated several times.

**Comment by quantumfusion** [comment]
So... I have no idea what was causing those problems. However, I pushed a promotion up to prod and it looks like it went fine.

Btw, @scottnuma what is up with this `WIP` man. Gotta keep that git history _fresh_... I mean **clean**.

Also, just noticed that you mention the need to monitor after deployment. Dokku supports post-deploy checks, so it may be worthwhile to look into adding some scripts there to confirm a successful deploy.

**Comment by scottnuma** [comment]
Mm, didn't pay attention to renaming. I'll get that for the future

Will look in to post-deploy checks stuff

**Pull request merged**
