### PR TITLE
Update due date for scholarship

### PR DESCRIPTION
**Pull request by quantumfusion**
Link: http://linode.matthewchang.com/programs/scholarship

Updated the due date for scholarship app.

**Note**: Please do not merge and immediately deploy. If possible, can I get approval so that I may coordinate with @dwai213 on the messaging to the teams.

### CODE REVIEW

**Comment by dwai213** [comment]
Do we want to make explicit here that teacher recommendations have a different due date?

**Comment by quantumfusion** [comment]
We haven't in the past. I don't see any reason to, especially based on my comments on the other PR.

**Comment by quantumfusion** [comment]
By the way, @kev-chien , we're just pushing master to dokku, correct? I have release branches on scholarship, so wanted to verify that you guys weren't doing that for website.

**Comment by kev-chien** [comment]
@quantumfusion  yup, we're just pushing master to dokku

**Pull request merged**
