### PR TITLE
Close #149 with real names

### LINKED ISSUE #149: Swap out usernames for actual names on blog
Blog entries are not longer tied to user accounts, so it doesn't make sense to have usernames there.

### PR DESCRIPTION
**Pull request by scottnuma**

### CODE REVIEW

**Comment by cwang395** [comment]
How do we prevent the example post from showing up on the website?

**Comment by jiangdaniel** [comment]
Whoops, we did not expect that to happen. Scott is looking into it

**Comment by cwang395** [comment]
Yeah, apologies, when I tested it on my machine the draft didn't show up, but when I pushed it to production it did ._.

**Comment by cwang395** [comment]
I'm going to revert this for now so we don't have an example post floating at the top of our blog. It is strange that the draft post should appear, since supposedly posts in the `_drafts/` folder don't show up. Let me know if you make progress :)

**Pull request merged**
