### PR TITLE
Close #161

### LINKED ISSUE #161: Inline hyperlinks difficult to see
The colors chosen for text make inline hyperlinks difficult to see (on some displays, at least). 
image

### PR DESCRIPTION
**Pull request by OvisCanadensis**

### CODE REVIEW

**Comment by cwang395** [comment]
I hesitate to add a new class whose sole purpose is to make some links yellow. Maybe we should just make all `<a>` tags yellow?

**Comment by jiangdaniel** [comment]
Christian tried that, and it made too many links yellow.  Like, all of the footer social media icons turned yellow too.

**Comment by quantumfusion** [comment]
If I remember correctly, the CSS parser is relatively simple, so if you establish apply a style to a class that is defined only for a specific region, such as inside a main content div you should be able to limit the scope of what anchor tags are made yellow. I'm guessing applying the style only to ```.container a``` you should get reasonable results.

**Comment by cwang395** [comment]
Yeah, I'm thinking of keeping links the same color but also making them underlined so they stand out more. You can see the changes at my repo's GitHub Pages site: http://cwang395.github.io/website/

Let me know what you think!

**Comment by cwang395** [comment]
Closed by #183

**Pull request closed without merging**
