### PR TITLE
[DO NOT MERGE] Test GitHub actions permissivenesss

### PR DESCRIPTION
**Pull request by scottnuma**
- Testing GitHub Actions
- Do not merge
- Do not pass go

### CODE REVIEW

**Review by dwai213 — APPROVED** [review]
LGTM how education

**Comment by scottnuma** [comment]
Curious why there are no actions running

**Comment by scottnuma** [comment]
> In order to protect public repositories for malicious users we run all pull request workflows raised from repository forks with a read-only token and no access to secrets. This makes common workflows like labeling or commenting on pull requests very difficult.
[source](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/)

**Comment by scottnuma** [comment]
We're not going to be able to run staging deploys from forks / random internet people / people w/o write access to the website

**Comment by scottnuma** [comment]
It looks like it worked here because I created a PR directly in the repo with the same SHA.

**Pull request closed without merging**
