### PR TITLE
Create Docker to Jekyll Interactive Mode Bash File

### PR DESCRIPTION
**Pull request by scottnuma**

### CODE REVIEW

**Comment by scottnuma** [comment]
close #176

**Comment by scottnuma** [comment]
Also resolved Ram's merge conflict

**Comment by cwang395** [comment]
Hi Scott, do you think you could just include the Docker-related changes in this pull request? Vivien says #229 isn't ready to be merged yet 😛

**Comment by scottnuma** [comment]
Separated from #229 and reverted out to mostly Docker (y)

**Pull request merged**
