### PR TITLE
Use yml files to generate pie team members

### PR DESCRIPTION
**Pull request by jiangdaniel**

### CODE REVIEW

**Comment by dwai213** [comment]
Looks hot af.
Would recommend however that the **url** field inside your .yml be changed to **picture** for a code clarity perspective

**Comment by jiangdaniel** [comment]
Agreed.  I'll try to make the change tomorrow.  Thanks!

**Comment by jiangdaniel** [comment]
Changed all 'url' properties to 'picture' 👍

**Comment by dwai213** [comment]
💯

**Pull request merged**
