### PR TITLE
Added Foundation page under first menu

### PR DESCRIPTION
**Pull request by dwai213**
- Also added tabs to team.html so that advisors/alumni are behind the staff

### CODE REVIEW

**Comment by cwang395** [comment]
Hi Dennis,

This page looks important! A couple of notes:
- Unless you have a very complex layout, it's not necessary to nest rows inside columns. The HTML will be cleaner if you avoid using new rows for every section, and it will make the page look better at smaller screen sizes because it preserves the left and right padding of the container div.
- Avoid divs that don't have any styles associated with them, as they don't do anything and really clutter up the HTML.
- What does wrapping the contact information in tildes do?
    - Also, why use [dot] in the email address rather than actual dots? The rest of the site uses dots.
- There is enough formatting on this page that it may just make more sense to make it a .html file rather than a .md file, but this is not as important.

Do we need this page on the website before Thursday? If not, I'd be happy to clean up the page a bit and push the code then.

**Comment by jiangdaniel** [comment]
IIRC, Dennis used the [dot] syntax in order to prevent bots from scraping the email address and sending spam to it.

**Comment by dwai213** [comment]
Herro

Thanks for the feedback!
- You can take a look at what tildes do [here](http://denniswai.com/website/)
- We can rename it to .html, it's cool.
- Can you point out what divs doesn't have styles?
- Nesting rows inside column, ok I will drop those rows. Thanks for the tip

It would be nice if we can deploy this before Kickoff :)

**Comment by cwang395** [comment]
Hi Dennis,

Your link to the tildes leads to http://denniswai.com/website/ :(

Should we give similar treatment to all the other emails on the website?

**Comment by dwai213** [comment]
My bad, the tildes can be seen here
<http://denniswai.com/website/about/foundation.html>

With regards to email, probably, if they are in plaintext.

Finally, I am trying to remove nested rows inside columns but having some difficulty
Right now, it looks like [this](https://www.dropbox.com/s/6vzhl93zcuex9nx/Screenshot%202016-02-23%2010.36.39.png?dl=0), where Donate is inline with the text that belongs with it. I attached the source below, do you or anyone else have any ideas why?

```
---
layout: markdown
title: Foundation
hero-image: url(../assets/images/stock-images/sponsors.jpg)
hero-message: The Pioneers in Engineering Foundation
title: Foundation
---
<div class="col-md-7"> <!-- first colummn -->

<div markdown="1">
## Mission
The Pioneers in Engineering Foundation is an independent, tax-exempt 501(c)(3) non-profit organization. Its mission is to promote STEM education through an exciting, mentor-based process.

## Donate
Donations to PiE are tax-deductible subject to federal and state charitable giving rules. If you would like to make a donation, please [donate online now]({{ "/support-pie/donate.html" | prepend: site.baseurl }}), or [email us](mailto:foundation@pioneers.berkeley.edu) to arrange your gift.

## Board of Directors and Executive Officers
The PiE Foundation is led by a board of current and former PiE members.

<div class="col-md-6">
<div markdown="1">
#### Executive Officers
* Dennis Wai
* Robert Luan
* Douglas Hutchings
</div>
</div>

<div class="col-md-6">
<div markdown="1">
#### Board Members
* Xiao-Yu Fu
* Vanathi Ganesh
* Douglas Hutchings
* Ryan Julian
* Nikita Kitaev
* Allen Li
* William Li
* Winston Long
* Robert Luan
* Tomoya Ogura
</div>
</div>

## Acknowledgement
In 2015, Pioneers in Engineering obtained 501(c)(3) nonprofit status with the help of [Michael M. Rosen](http://www.fr.com/michael-m-rosen/) of [Fish and Richardson](http://www.fr.com/).
</div>

</div> <!-- end of first column -->
```

**Comment by jiangdaniel** [comment]
I would attach an id to the “Donate“ heading, and set its CSS display property to “display: block;”
Or maybe set its width to 100%

However, I haven’t really worked with markdown files, so I don’t really know whether you can attach an id to the heading or not.

**Comment by jiangdaniel** [comment]
Setting the display to “block” or the width to 100% should both yield the same result of having the heading take up the full width available.

**Comment by cwang395** [comment]
+1 to Daniel's comment about how setting display to "block" should make the text start on the next line. But `<h>` tags (which I think `## Donate` compiles down into) should already have `display: block` by default. It's hard to tell what's going on without looking at the code; is there a chance you can push this to your `gh-pages` branch so we can look at it in the web inspector?

**Comment by dwai213** [comment]
Yep, just did
<http://denniswai.com/website/about/foundation.html>

I think the bug stems from
```
#donate {
  float: left;
  margin-right: $spacing-unit;
}
```
in _styles.scss

My `## Donate` heading seems to trigger it and cause it to float left instead of taking up the entire width. Changing the heading can be one solution. Alternatively, can do something to avoid using the #donate style?

**Comment by jiangdaniel** [comment]
Can you clarify what you mean when you say that you want to “avoid using the #donate” style?  Do you mean that you would rather avoid using CSS/SCSS?

**Comment by dwai213** [comment]
Sorry to be unclear

If I use `## Donate` as part of my page, then the rendered HTML is `<h2 id="donate">Donate</h2>` 
That `id=` then invokes the #donate style in your CSS/SCSS files, which unintentionally causes my heading to float to the left.

I think I want to avoid CSS/SCSS if I can since I have such a simple page so I just renamed my heading to `Donate to Us`

**Comment by jiangdaniel** [comment]
Ah, I see.  I don’t know anything about markdown, so I’m not sure if there is a way to avoid the auto-generated id tag.  Someone could probably easily rename the existing #donate CSS to something else.

**Comment by dwai213** [comment]
@scottnuma and @OvisCanadensis 

Hey you two, you guys added 
```
#donate {
  float: left;
  margin-right: $spacing-unit;
}
```
to `_styles.scss` 
right?
Where are you guys currently using it?

**Comment by jiangdaniel** [comment]
If you search the entire website folder for id=“donate”, then you should be able to find it.

In Atom, it’s Cmd+Shift+F to search the entire project folder. I’m not sure which text editor you are using though

**Comment by dwai213** [comment]
Yeah a search tells me it's just me (inadvertently) using it. I am going to run it by them to make everything's alright though.

**Comment by scottnuma** [comment]
Ah, that tag was probably an old tag we used for formatting on the donate page. It looks like we got rid of it, so any changes you make to the tag are fine.

**Comment by dwai213** [comment]
Gotcha, thanks for the reply.
I added another commit that removes the offending CSS from `_styles.scss`

**Pull request closed without merging**
