### PR TITLE
Add 2016 finalists blog post and pictures

### PR DESCRIPTION
**Pull request by jesca**

### CODE REVIEW

**Comment by cwang395** [comment]
Sorry, merged this pull request a bit prematurely. Did you add the images to your commits? Take a look at my [GitHub Pages demo](http://cwang395.github.io/website/blog/) to see what the changes look like.

**Comment by jesca** [comment]
Looks like it's not getting the image source 
screen shot 2016-05-01 at 11 58 43 pm

**Comment by jesca** [comment]
Ah - i left them out of the pull request - i submitted another pull request for the pictures

**Comment by cwang395** [comment]
Awesome! Thanks for being patient, as you can see we're still working out the kinks with blogging.

**Pull request merged**
